// optional for part 2 of challenge


// connection

// list a set of menu options:
    // View Products for Sale
        // if selected, will list every available item ID, name, price, and quantity
    // View Low Inventory
        // will list all items with an inventory count lower than 5
    // Add to Inventory
        // display a prompt to allow manager to "add more" of any item currently in store
    // Add New Product  
        // allow to add a completely new product to store


